<?php

namespace VD\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByEmail($email)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT p FROM VDAccountBundle:User p WHERE p.email = :email')
            ->setParameter('email', $email);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

//    public function findOneByIdJoinedToCategory($id)
//    {
//        $query = $this->getEntityManager()
//            ->createQuery('SELECT p, c FROM NFQDariuskStoreBundle:Product p
//              JOIN p.category c
//              WHERE p.id = :id'
//        )->setParameter('id', $id);
//
//        try {
//            return $query->getSingleResult();
//        } catch (\Doctrine\ORM\NoResultException $e) {
//            return null;
//        }
//    }
}