parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     triton1_vd
    database_user:     triton1_vd
    database_password: bli8das

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            jas093u0ajfp[f;qj94j03q9hg0qpwj;f-9jq10f
