vd_account_index:
    pattern:  /
    defaults: { _controller: VDAccountBundle:Default:index }
vd_account_register:
    pattern:  /register
    defaults: { _controller: VDAccountBundle:Default:register }
vd_account_register_success:
    pattern:  /register/success
    defaults: { _controller: VDAccountBundle:Default:registerSuccess }
vd_account_login:
    pattern:  /login
    defaults: { _controller: VDAccountBundle:Default:login }
vd_account_login_check:
    pattern:  /login_check
    defaults: { _controller: VDAccountBundle:Default:loginCheck }
vd_account_logout:
    pattern:  /logout
    defaults: { _controller: VDAccountBundle:Default:logout }
vd_add_income:
    pattern: /incomeAdd
    defaults: { _controller: VDAccountBundle:Income:add }
