VD\AccountBundle\Entity:
    properties:
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - MinLength: { limit: 6 }
        name:
            - NotBlank: ~