VD\AccountBundle\Entity:
    properties:
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Length:
                  min: 6
                  minMessage: "Slaptažodis turi būti bent 6 simbolių"
        name:
            - NotBlank: ~